package com.mmj.core.mapper.auto;

import com.mmj.core.model.auto.AdminMsg;
import com.mmj.core.model.auto.AdminMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_msg
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    long countByExample(AdminMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_msg
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    int deleteByExample(AdminMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_msg
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    int insert(AdminMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_msg
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    int insertSelective(AdminMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_msg
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    List<AdminMsg> selectByExample(AdminMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_msg
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") AdminMsg record, @Param("example") AdminMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_msg
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    int updateByExample(@Param("record") AdminMsg record, @Param("example") AdminMsgExample example);
}