package com.mmj.core.mapper.auto;

import com.mmj.core.model.auto.BigKind;
import com.mmj.core.model.auto.BigKindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BigKindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    long countByExample(BigKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    int deleteByExample(BigKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    int insert(BigKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    int insertSelective(BigKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    List<BigKind> selectByExample(BigKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") BigKind record, @Param("example") BigKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    int updateByExample(@Param("record") BigKind record, @Param("example") BigKindExample example);
}