package com.mmj.core.mapper.auto;

import com.mmj.core.model.auto.UserLogin;
import com.mmj.core.model.auto.UserLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    long countByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    int deleteByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    int insert(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    int insertSelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    List<UserLogin> selectByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserLogin record, @Param("example") UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    int updateByExample(@Param("record") UserLogin record, @Param("example") UserLoginExample example);
}