package com.mmj.core.model.auto;

public class AdminMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_msg.id
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_msg.admin_name
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_msg.sex
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_msg.username
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_msg.password
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_msg.telephone
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_msg.email
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_msg.level
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_msg.id
     *
     * @return the value of admin_msg.id
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_msg.id
     *
     * @param id the value for admin_msg.id
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_msg.admin_name
     *
     * @return the value of admin_msg.admin_name
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_msg.admin_name
     *
     * @param adminName the value for admin_msg.admin_name
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_msg.sex
     *
     * @return the value of admin_msg.sex
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_msg.sex
     *
     * @param sex the value for admin_msg.sex
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_msg.username
     *
     * @return the value of admin_msg.username
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_msg.username
     *
     * @param username the value for admin_msg.username
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_msg.password
     *
     * @return the value of admin_msg.password
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_msg.password
     *
     * @param password the value for admin_msg.password
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_msg.telephone
     *
     * @return the value of admin_msg.telephone
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_msg.telephone
     *
     * @param telephone the value for admin_msg.telephone
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_msg.email
     *
     * @return the value of admin_msg.email
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_msg.email
     *
     * @param email the value for admin_msg.email
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_msg.level
     *
     * @return the value of admin_msg.level
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_msg.level
     *
     * @param level the value for admin_msg.level
     *
     * @mbg.generated Thu May 23 13:52:58 CST 2019
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }
}