package com.mmj.core.model.auto;

import java.util.ArrayList;
import java.util.List;

public class BigKindExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public BigKindExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBigKindNameIsNull() {
            addCriterion("big_kind_name is null");
            return (Criteria) this;
        }

        public Criteria andBigKindNameIsNotNull() {
            addCriterion("big_kind_name is not null");
            return (Criteria) this;
        }

        public Criteria andBigKindNameEqualTo(String value) {
            addCriterion("big_kind_name =", value, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindNameNotEqualTo(String value) {
            addCriterion("big_kind_name <>", value, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindNameGreaterThan(String value) {
            addCriterion("big_kind_name >", value, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindNameGreaterThanOrEqualTo(String value) {
            addCriterion("big_kind_name >=", value, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindNameLessThan(String value) {
            addCriterion("big_kind_name <", value, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindNameLessThanOrEqualTo(String value) {
            addCriterion("big_kind_name <=", value, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindNameLike(String value) {
            addCriterion("big_kind_name like", value, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindNameNotLike(String value) {
            addCriterion("big_kind_name not like", value, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindNameIn(List<String> values) {
            addCriterion("big_kind_name in", values, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindNameNotIn(List<String> values) {
            addCriterion("big_kind_name not in", values, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindNameBetween(String value1, String value2) {
            addCriterion("big_kind_name between", value1, value2, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindNameNotBetween(String value1, String value2) {
            addCriterion("big_kind_name not between", value1, value2, "bigKindName");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgIsNull() {
            addCriterion("big_kind_msg is null");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgIsNotNull() {
            addCriterion("big_kind_msg is not null");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgEqualTo(String value) {
            addCriterion("big_kind_msg =", value, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgNotEqualTo(String value) {
            addCriterion("big_kind_msg <>", value, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgGreaterThan(String value) {
            addCriterion("big_kind_msg >", value, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgGreaterThanOrEqualTo(String value) {
            addCriterion("big_kind_msg >=", value, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgLessThan(String value) {
            addCriterion("big_kind_msg <", value, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgLessThanOrEqualTo(String value) {
            addCriterion("big_kind_msg <=", value, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgLike(String value) {
            addCriterion("big_kind_msg like", value, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgNotLike(String value) {
            addCriterion("big_kind_msg not like", value, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgIn(List<String> values) {
            addCriterion("big_kind_msg in", values, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgNotIn(List<String> values) {
            addCriterion("big_kind_msg not in", values, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgBetween(String value1, String value2) {
            addCriterion("big_kind_msg between", value1, value2, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindMsgNotBetween(String value1, String value2) {
            addCriterion("big_kind_msg not between", value1, value2, "bigKindMsg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgIsNull() {
            addCriterion("big_kind_img is null");
            return (Criteria) this;
        }

        public Criteria andBigKindImgIsNotNull() {
            addCriterion("big_kind_img is not null");
            return (Criteria) this;
        }

        public Criteria andBigKindImgEqualTo(String value) {
            addCriterion("big_kind_img =", value, "bigKindImg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgNotEqualTo(String value) {
            addCriterion("big_kind_img <>", value, "bigKindImg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgGreaterThan(String value) {
            addCriterion("big_kind_img >", value, "bigKindImg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgGreaterThanOrEqualTo(String value) {
            addCriterion("big_kind_img >=", value, "bigKindImg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgLessThan(String value) {
            addCriterion("big_kind_img <", value, "bigKindImg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgLessThanOrEqualTo(String value) {
            addCriterion("big_kind_img <=", value, "bigKindImg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgLike(String value) {
            addCriterion("big_kind_img like", value, "bigKindImg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgNotLike(String value) {
            addCriterion("big_kind_img not like", value, "bigKindImg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgIn(List<String> values) {
            addCriterion("big_kind_img in", values, "bigKindImg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgNotIn(List<String> values) {
            addCriterion("big_kind_img not in", values, "bigKindImg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgBetween(String value1, String value2) {
            addCriterion("big_kind_img between", value1, value2, "bigKindImg");
            return (Criteria) this;
        }

        public Criteria andBigKindImgNotBetween(String value1, String value2) {
            addCriterion("big_kind_img not between", value1, value2, "bigKindImg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table big_kind
     *
     * @mbg.generated do_not_delete_during_merge Mon May 20 11:41:57 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table big_kind
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}