package com.mmj.core.model.auto;

public class BigKind {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_kind.id
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_kind.big_kind_name
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    private String bigKindName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_kind.big_kind_msg
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    private String bigKindMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_kind.big_kind_img
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    private String bigKindImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_kind.id
     *
     * @return the value of big_kind.id
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_kind.id
     *
     * @param id the value for big_kind.id
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_kind.big_kind_name
     *
     * @return the value of big_kind.big_kind_name
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public String getBigKindName() {
        return bigKindName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_kind.big_kind_name
     *
     * @param bigKindName the value for big_kind.big_kind_name
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public void setBigKindName(String bigKindName) {
        this.bigKindName = bigKindName == null ? null : bigKindName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_kind.big_kind_msg
     *
     * @return the value of big_kind.big_kind_msg
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public String getBigKindMsg() {
        return bigKindMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_kind.big_kind_msg
     *
     * @param bigKindMsg the value for big_kind.big_kind_msg
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public void setBigKindMsg(String bigKindMsg) {
        this.bigKindMsg = bigKindMsg == null ? null : bigKindMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_kind.big_kind_img
     *
     * @return the value of big_kind.big_kind_img
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public String getBigKindImg() {
        return bigKindImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_kind.big_kind_img
     *
     * @param bigKindImg the value for big_kind.big_kind_img
     *
     * @mbg.generated Mon May 20 11:41:57 CST 2019
     */
    public void setBigKindImg(String bigKindImg) {
        this.bigKindImg = bigKindImg == null ? null : bigKindImg.trim();
    }
}