package com.mmj.core.model.auto;

public class SmallKind {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_kind.id
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_kind.big_id
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    private Integer bigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_kind.big_kind_name
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    private String bigKindName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_kind.small_kind_name
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    private String smallKindName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_kind.small_kind_msg
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    private String smallKindMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_kind.small_kind_img
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    private String smallKindImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_kind.id
     *
     * @return the value of small_kind.id
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_kind.id
     *
     * @param id the value for small_kind.id
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_kind.big_id
     *
     * @return the value of small_kind.big_id
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public Integer getBigId() {
        return bigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_kind.big_id
     *
     * @param bigId the value for small_kind.big_id
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public void setBigId(Integer bigId) {
        this.bigId = bigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_kind.big_kind_name
     *
     * @return the value of small_kind.big_kind_name
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public String getBigKindName() {
        return bigKindName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_kind.big_kind_name
     *
     * @param bigKindName the value for small_kind.big_kind_name
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public void setBigKindName(String bigKindName) {
        this.bigKindName = bigKindName == null ? null : bigKindName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_kind.small_kind_name
     *
     * @return the value of small_kind.small_kind_name
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public String getSmallKindName() {
        return smallKindName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_kind.small_kind_name
     *
     * @param smallKindName the value for small_kind.small_kind_name
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public void setSmallKindName(String smallKindName) {
        this.smallKindName = smallKindName == null ? null : smallKindName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_kind.small_kind_msg
     *
     * @return the value of small_kind.small_kind_msg
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public String getSmallKindMsg() {
        return smallKindMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_kind.small_kind_msg
     *
     * @param smallKindMsg the value for small_kind.small_kind_msg
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public void setSmallKindMsg(String smallKindMsg) {
        this.smallKindMsg = smallKindMsg == null ? null : smallKindMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_kind.small_kind_img
     *
     * @return the value of small_kind.small_kind_img
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public String getSmallKindImg() {
        return smallKindImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_kind.small_kind_img
     *
     * @param smallKindImg the value for small_kind.small_kind_img
     *
     * @mbg.generated Fri May 31 18:49:53 CST 2019
     */
    public void setSmallKindImg(String smallKindImg) {
        this.smallKindImg = smallKindImg == null ? null : smallKindImg.trim();
    }
}