package com.mmj.core.model.auto;

import org.apache.ibatis.type.Alias;

@Alias("userLogin")
public class UserLogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.id
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.email
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.password
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.ninck_name
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    private String ninckName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.id
     *
     * @return the value of user_login.id
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.id
     *
     * @param id the value for user_login.id
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.email
     *
     * @return the value of user_login.email
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.email
     *
     * @param email the value for user_login.email
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.password
     *
     * @return the value of user_login.password
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.password
     *
     * @param password the value for user_login.password
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.ninck_name
     *
     * @return the value of user_login.ninck_name
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    public String getNinckName() {
        return ninckName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.ninck_name
     *
     * @param ninckName the value for user_login.ninck_name
     *
     * @mbg.generated Mon May 20 10:50:44 CST 2019
     */
    public void setNinckName(String ninckName) {
        this.ninckName = ninckName == null ? null : ninckName.trim();
    }
}